name: querido_diario
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  toastification: ^3.0.3
  font_awesome_flutter: ^10.9.1
  animated_bottom_navigation_bar: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/4.jpeg
    - assets/images/6.jpeg
    - assets/images/7.jpeg
    - assets/images/8.jpeg
    - assets/images/9.jpeg
    - assets/images/10.jpeg
    - assets/images/11.jpeg
    - assets/images/card-images/9.png
    - assets/images/card-images/card-image.jpeg
    - assets/images/card-images/card-image1.jpeg
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
