class Assets {
  static const bg1 = 'assets/images/1.jpeg';
  static const bg2 = 'assets/images/2.jpeg';
  static const bg3 = 'assets/images/3.jpeg';
  static const bg4 = 'assets/images/4.jpeg';
  static const bg6 = 'assets/images/6.jpeg';
  static const bg7 = 'assets/images/7.jpeg';
  static const bg8 = 'assets/images/8.jpeg';
  static const bg81 = 'assets/images/8.png';
  static const bg9 = 'assets/images/9.jpeg';
  static const bg10 = 'assets/images/10.jpeg';
  static const bg11 = 'assets/images/11.jpeg';
  static const cardImage1 = 'assets/images/card-images/9.png';
  static const cardImage2 = 'assets/images/card-images/card-image.jpeg';
  static const cardImage3 = 'assets/images/card-images/card-image1.jpeg';
}

const List<String> cardImages = [
  Assets.cardImage1,
  Assets.cardImage2,
  Assets.cardImage3,
];

// Example phrases to rotate through if none provided
const List<String> defaultPhrases = [
  'Albert Einstein - A imaginação é mais importante que o conhecimento.',
  'Mahatma Gandhi - Seja a mudança que você deseja ver no mundo.',
  'Nelson Mandela - A educação é a arma mais poderosa que você pode usar para mudar o mundo.',
  'Steve Jobs - A única maneira de fazer um excelente trabalho é amar o que você faz.',
  'Martin Luther King Jr. - Eu tenho um sonho de ver meus filhos julgados pelo caráter, não pela cor da pele.',
  'Confúcio - A maior glória não está em nunca cair, mas em levantar-se toda vez que caímos.',
  'Sêneca - Não é porque as coisas são difíceis que não ousamos; é porque não ousamos que elas são difíceis.',
  'Aristóteles - Nós somos o que repetidamente fazemos. A excelência, portanto, não é um ato, mas um hábito.',
  'Dalai Lama - A felicidade não é algo pronto. Ela vem de suas próprias ações.',
  'Friedrich Nietzsche - Aquilo que não me mata, me fortalece.',
  'Leonardo da Vinci - Aprender é a única coisa de que a mente nunca se cansa, nunca tem medo e nunca se arrepende.',
  'Platão - A direção em que a educação inicia um homem determinará seu futuro.',
  'Napoleão Bonaparte - A vitória pertence ao mais perseverante.',
  'Walt Disney - Se você pode sonhar, você pode fazer.',
  'Henry Ford - Se você pensa que pode ou pensa que não pode, de qualquer forma você está certo.',
  'Abraham Lincoln - A melhor maneira de prever o futuro é criá-lo.',
  'Buda - O que somos é resultado do que pensamos.',
  'Sócrates - Conhece-te a ti mesmo e conhecerás o universo e os deuses.',
  'Vincent van Gogh - O que seria da vida se não tivéssemos coragem de tentar algo novo?',
  'Pablo Picasso - A inspiração existe, mas ela precisa te encontrar trabalhando.',
  'Charles Chaplin - A persistência é o caminho do êxito.',
  'Eleanor Roosevelt - Ninguém pode fazê-lo se sentir inferior sem o seu consentimento.',
  'Theodore Roosevelt - Acredite que você pode, assim você já está no meio do caminho.',
  'Bruce Lee - Não reze por uma vida fácil, reze por forças para suportar uma difícil.',
  'Fernando Pessoa - Tudo vale a pena quando a alma não é pequena.',
  'Clarice Lispector - Liberdade é pouco. O que eu desejo ainda não tem nome.',
  'Cora Coralina - Feliz aquele que transfere o que sabe e aprende o que ensina.',
  'Augusto Cury - Sonhe grande, comece pequeno, mas comece.',
  'Paulo Coelho - Quando você quer alguma coisa, todo o universo conspira para que você realize seu desejo.',
  'Albert Schweitzer - Sucesso não é a chave para a felicidade. Felicidade é a chave para o sucesso.',
  'Benjamin Franklin - Energia e persistência conquistam todas as coisas.',
  'Isaac Newton - Se enxerguei mais longe, foi por estar sobre ombros de gigantes.',
  'Oprah Winfrey - Transforme suas feridas em sabedoria.',
  'Bill Gates - É bom celebrar o sucesso, mas é mais importante aprender com o fracasso.',
  'Marie Curie - Nada na vida deve ser temido, apenas compreendido.',
  'René Descartes - Penso, logo existo.',
  'Sun Tzu - A vitória está reservada para aqueles que estão dispostos a pagar o preço.',
  'Lao Tsé - Uma jornada de mil milhas começa com um único passo.',
  'Confúcio - Transportai um punhado de terra todos os dias e fareis uma montanha.',
  'Marcus Aurelius - A felicidade da sua vida depende da qualidade dos seus pensamentos.',
  'Epicteto - Não é o que acontece com você, mas como você reage ao que acontece que importa.',
  'Lucius Annaeus Seneca - A sorte é o que acontece quando a preparação encontra a oportunidade.',
  'Victor Hugo - Mesmo a noite mais sombria terminará com o nascer do sol.',
  'Johann Goethe - Saber não é suficiente; precisamos aplicar. Querer não é suficiente; precisamos fazer.',
  'William Shakespeare - Nossas dúvidas são traidoras e nos fazem perder o bem que poderíamos conquistar.',
  'George Bernard Shaw - O progresso é impossível sem mudança; e aqueles que não podem mudar suas mentes não podem mudar nada.',
  'Thomas Edison - Eu não falhei. Apenas descobri 10 mil maneiras que não funcionam.',
  'Ralph Waldo Emerson - O que está atrás de nós e o que está à nossa frente são coisas pequenas comparadas ao que está dentro de nós.',
  'Helen Keller - A vida é uma aventura ousada ou não é nada.',
  'Henry David Thoreau - Vá confiantemente na direção dos seus sonhos. Viva a vida que você imaginou.',
  'Charles Darwin - Não é o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta às mudanças.',
  'Isaac Asimov - A violência é o último refúgio do incompetente.',
  'Nikola Tesla - O presente é deles, o futuro é meu.',
  'Elon Musk - Quando algo é importante o suficiente, você faz mesmo que as probabilidades não estejam a seu favor.',
  'Jeff Bezos - A vida é muito curta para estar cercado de pessoas negativas.',
  'Stephen Hawking - A inteligência é a capacidade de se adaptar à mudança.',
  'Malala Yousafzai - Um livro, uma caneta, uma criança e um professor podem mudar o mundo.',
  'John Lennon - A vida é o que acontece enquanto você está ocupado fazendo outros planos.',
  'Bob Marley - Não viva para que a sua presença seja notada, mas para que a sua falta seja sentida.',
  'Chico Xavier - Embora ninguém possa voltar atrás e fazer um novo começo, qualquer um pode começar agora e fazer um novo fim.',
  'Mario Quintana - O segredo é não correr atrás das borboletas, é cuidar do jardim para que elas venham até você.',
  'Cecília Meireles - Liberdade é um sonho eterno.',
  'Mário Sérgio Cortella - Faça o seu melhor, na condição que você tem, enquanto você não tem condições melhores para fazer melhor ainda.',
  'Leandro Karnal - O sentido da vida é dar sentido à vida.',
  'Rubem Alves - Há escolas que são gaiolas e há escolas que são asas.',
  'Sigmund Freud - Ser totalmente honesto consigo mesmo é um bom exercício.',
  'Carl Jung - Quem olha para fora, sonha; quem olha para dentro, desperta.',
  'Albert Camus - No meio do inverno aprendi que havia em mim um verão invencível.',
  'George Orwell - Liberdade é o direito de dizer às pessoas o que elas não querem ouvir.',
  'Virginia Woolf - Não há barreira, fechadura ou tranca que se possa impor à liberdade da minha mente.',
  'Jane Austen - Não há nada que eu não faria por aqueles que são realmente meus amigos.',
  'Frida Kahlo - Onde não puderes amar, não te demores.',
  'Simone de Beauvoir - Que nada nos defina, que nada nos sujeite, que a liberdade seja a nossa própria substância.',
  'Rumi - Ontem eu era inteligente e queria mudar o mundo. Hoje sou sábio e quero mudar a mim mesmo.',
  'Khalil Gibran - O sofrimento é o instrumento pelo qual as almas mais fortes são forjadas.',
  'Epiteto - A liberdade está em ser senhor de si mesmo.',
  'Machado de Assis - Cada qual sabe amar a seu modo; o modo pouco importa, o essencial é que saiba amar.',
  'Guimarães Rosa - O que a vida quer da gente é coragem.',
  'José Saramago - Dentro de nós há algo que não tem nome, e isso é o que somos.',
  'Fernando Sabino - No fim tudo dá certo, e se não deu certo é porque ainda não chegou ao fim.',
  'Ayrton Senna - Se você quer ser bem-sucedido, precisa ter dedicação total, buscar seu último limite e dar o melhor de si.',
  'Pelé - O sucesso não é acidente. É trabalho duro, perseverança, aprendizado, estudo e amor pelo que se faz.',
  'Lula Santos - Nada do que foi será, de novo do jeito que já foi um dia.',
  'Renato Russo - É preciso amar as pessoas como se não houvesse amanhã.',
  'Raul Seixas - Sonho que se sonha só é só um sonho, mas sonho que se sonha junto é realidade.',
  'Cazuza - O tempo não para.',
  'Amyr Klink - Um homem precisa viajar. Por sua conta, não por meio de histórias, imagens, livros ou TV.',
  'Oscar Niemeyer - Não é o ângulo reto que me atrai, mas a curva livre e sensual.',
  'Zilda Arns - O amor é a força mais poderosa do mundo.',
  'Papa Francisco - A esperança é audaciosa e sabe olhar além do conforto pessoal.',
  'Jesus Cristo - Ame o teu próximo como a ti mesmo.',
  'Madre Teresa de Calcutá - O importante não é quanto se dá, mas quanto amor se coloca no dar.',
  'Blaise Pascal - O coração tem razões que a própria razão desconhece.',
  'Voltaire - Posso não concordar com o que você diz, mas defenderei até a morte o seu direito de dizê-lo.',
  'Immanuel Kant - Age de tal maneira que a máxima de tua ação possa ser erigida em lei universal.',
  'Jean-Jacques Rousseau - O homem nasce livre, e por toda parte encontra-se acorrentado.',
  'Albert Einstein - A vida é como andar de bicicleta: para manter o equilíbrio, é preciso continuar se movendo.',
  'Aristóteles - A esperança é o sonho do homem acordado.',
  'Lao Tsé - Dominar os outros é força. Dominar a si mesmo é verdadeiro poder.',
  'Confúcio - Escolhe um trabalho de que gostes, e não terás que trabalhar nem um dia na tua vida.',
];

